package PoblarBaseDeDatos

import scalikejdbc._
import com.github.tototoshi.csv.CSVReader

import java.io.File

object CastCleanReplace extends App{
  Class.forName("com.mysql.cj.jdbc.Driver")
  ConnectionPool.singleton("jdbc:mysql://localhost:3306/movie_dataset", "root", "abcd1234")
  implicit val session: DBSession = AutoSession


  val reader = CSVReader.open(new File("/Users/josue/Desktop/Universidad/Practicum/movie_dataset.csv"))
  val data = reader.allWithHeaders()
  reader.close()


  val cast = data.flatMap(elem => elem.get("cast"))
  //Función que filtra aquellos Steven Lee Edwards, pues es un caso aisaldo.
  val tempCast = cast.map(x => x
    //Corrección de caraácteres especiales
    .replace("a\\u0301", "á")
    .replace("\\u00e1", "á")
    .replace("\\u00c1", "Á")
    .replace("\\u00c5", "Å")
    .replace("\\u00c0", "À")
    .replace("\\u00e5", "å")
    .replace("\\u00e4", "ä")
    .replace("\\u00e0", "à")
    .replace("\\u0101", "ā")
    .replace("\\u1ea3", "à")
    .replace("\\u00e6", "æ")
    .replace("\\u00df", "ß")
    .replace("\\u00e7", "ç")
    .replace("\\u010d", "č")
    .replace("\\u0107", "ć")
    .replace("\\u011f", "ğ")
    .replace("\\u00e9", "é")
    .replace("\\u1ec1", "ề")
    .replace("\\u00e8", "è")
    .replace("\\u00ea", "ê")
    .replace("\\u00eb", "ë")
    .replace("\\u1ebf", "ế")
    .replace("\\u00c9", "É")
    .replace("\\u00fa", "ú")
    .replace("\\u00fc", "ü")
    .replace("\\u016b", "ū")
    .replace("\\u00fb", "û")
    .replace("\\u00dc", "Ü")
    .replace("\\u00ed", "í")
    .replace("\\u00ef", "ï")
    .replace("\\u00ee", "î")
    .replace("\\u0131", "ı")
    .replace("\\u1ecb", "ị")
    .replace("\\u015e", "Ş")
    .replace("\\u0219", "ș")
    .replace("\\u015f", "ş")
    .replace("\\u0161", "š")
    .replace("\\u015b", "ś")
    .replace("\\u0160", "Š")
    .replace("\\u0144", "ń")
    .replace("\\u00f1", "ñ")
    .replace("\\u0110", "Đ")
    .replace("\\u00d8", "Ø")
    .replace("\\u00f8", "ø")
    .replace("\\u00f6", "ö")
    .replace("\\u00d3", "Ó")
    .replace("\\u00f3", "ó")
    .replace("\\u014d", "ō")
    .replace("\\u00f4", "ô")
    .replace("\\u00f6", "ö")
    .replace("\\u1ed7", "ỗ")
    .replace("\\u00f0", "ð")
    .replace("\\u0159", "ř")
    .replace("\\u2019", "’")
    .replace("\\u021b", "ț")
    .replace("\\u017e", "ž")
    .replace("\\u042e\\u043b\\u0438\\u044f \\u0421\\" +
      "u043d\\u0438\\u0433\\u0438\\u0440\\u044c", "Yuliya Snigir")
    .replace("\\u067e\\u06cc\\u0645\\u0627\\u0646 \\u0645\\u0639\\u0627\\u062f\\u06cc", "Payman Maadi")


    // Se únen los acrónimas, el espacio es el lugar con el que se une las anteriores palabras.
    .replace(" Jr.", "_Jr.")
    .replace(",_Jr", "_Jr.")
    .replace("A. ", "A._")
    .replace("F. ", "F._")
    .replace("A.J. ", "A._J. ")
    .replace("St. ", "St._")
    .replace(" L. ", " L._")
    .replace("S. ", "S._")
    .replace(" B. ", "_B. ")
    .replace(" E. ", "_E. ")
    .replace(" D. ", " D._")
    .replace(" C. ", "_C. ")
    .replace("R. ", "R._")
    .replace(" J. ", " J._")
    .replace(" T. ", " T._")
    .replace("T.I.", "T.I. ^")
    .replace(" H. ", " H._")
    .replace(" G. ", " G._")
    .replace(" P. ", " P._")
    .replace("M. ", "M._")
    .replace(" de la ", " de_la_")
    .replace(" de ", " de_")
    .replace(" La ", " La_")
    .replace(" Le ", " Le_")
    .replace(" De ", " De_")
    .replace(" Van ", " Van_")
    .replace(" van ", " van_")
    .replace(" San ", " San_")
    .replace(" II", "_II")
    .replace(" III", "_III")
    .replace(" Lo ", "_Lo ")
    .replace(" O. ", " O._")
    .replace(" Da ", " Da_")
    .replace(" V. ", " V._")
    .replace(" Des ", " Des_")
    .replace(" The ", " The_")
    .replace(" the ", " the_")
    .replace(" von ", " von_")
    .replace(" del ", " del_")

    //Nombres únicos // ^significa que el nombre anterior es único
    .replace("Panou", "Panou ^")
    .replace("RZA", "RZA ^")
    .replace("Taimak", "Taimak ^")
    .replace("Neha ", "Neha ^ ")
    .replace("Tabu", "Tabu ^")
    .replace("Will.i.am", "Will.i.am ^")
    .replace("Pelé", "Pelé ^")
    .replace("Rihanna", "Rihanna ^")
    .replace("Aaliyah", "Aaliyah ^")
    .replace("DMX", "DMX ^")
    .replace("Cher ", "Cher ^ ")
    .replace(" GQ", " GQ ^")
    .replace("Steve-O", "Steve-O ^")
    .replace("Vanity", "Vanity ^")
    .replace("Pink ", "Pink ^ ")
    .replace("Ginuwine", "Ginuwine ^")
    .replace("Björk", "Björk ^")
    .replace("Madonna", "Madonna ^")
    .replace("Aliya", "Aliya ^")
    .replace("Mo'Nique", "Mo'Nique ^")
    .replace("Godfrey", "Godfrey ^")
    .replace("Lalaine", "Lalaine ^")
    .replace("Eminem", "Eminem ^")
    .replace("Arletty", "Arletty ^")
    .replace("Ne-Yo", "Ne-Yo ^")
    .replace("Silverman Eve", "Silverman Eve ^")
    .replace(" Common", " Common ^")
    .replace(" Bilal", " Bilal ^")
    .replace("Washington Mario", "Washington Mario ^")
    .replace("Dempsey Mario", "Dempsey Mario ^")
    .replace("Wazheir Lena", "Wazheir Lena ^")
    .replace("Ludacris", "Ludacris ^")
    .replace("Ashanti", "Ashanti ^")
    .replace(" Mako", " Mako ^")
    .replace("Orianthi", "Orianthi ^")
    .replace("Maïwenn", "Maïwenn ^")
    .replace(" Dragon ", " Dragon ^ ")
    .replace(" Kajol ", " Kajol ^ ")
    .replace(" Luenell ", " Luenell ^ ")
    .replace("Rain Naomie", "Rain ^ Naomie")
    .replace(" Sarala ", " Sarala ^ ")
    .replace("Irvin Nelly", "Irvin Nelly ^")
    .replace(" Sinbad ", " Sinbad ^ ")
    .replace(" Amidou", " Amidou ^")
    .replace("Sting", "Sting ^")
    .replace("Litefoot", "Litefoot ^")
    .replace(" Ninja ", " Ninja ^ ")
    .replace(" Astro ", " Astro ^ ")
    .replace(" JoeyStarr ", " JoeyStarr ^ ")
    .replace(" Miyavi ", " Miyavi ^ ")
    .replace(" Redman ", " Redman ^ ")
    .replace("Raven-Symoné", "Raven-Symoné ^")
    .replace(" Rekha ", " Rekha ^ ")
    .replace(" Revathi ", " Revathi ^ ")
    .replace(" E-40 ", " E-40 ^ ")
    .replace("Xzibit", "Xzibit ^ ")
    .replace(" Jewel ", " Jewel ^ ")
    .replace("Krafft-Raschig", "Krafft-Raschig ^")
    .replace("Prabhas ", " Prabhas ^ ")
    .replace("RuPaul", "RuPaul ^")
    .replace("Brahmanandam", "Brahmanandam ^")
    .replace("Silambarasan", "Silambarasan ^")
    .replace(" Santhanam", " Santhanam ")
    .replace("Ice-T", "Ice-T ^")
    .replace(" Akon ", " Akon ^ ")
    .replace(" Santhanam ", " Santhanam ^ ")



    //Replace de nombres // _ significa espacio
    .replace("Steven Lee Edwards", "Steven Lee_Edwards")
    .replace("R.L._", "R._L.")
    .replace("Chris Ivan Cevic", "Chris_Ivan Cevic")
    .replace("Wilson Jermaine Heredia", "Wilson_Jermaine Heredia")
    .replace("O.L._Duke", "O._L. Duke")
    .replace("Jada Pinkett Smith", "Jada_Pinkett Smith")
    .replace("Sacha Baron Cohen", "Sacha_Baron Cohen")
    .replace("Keenen Ivory Wayans", "Keenen_Ivory Wayans")
    .replace(" David Alan Grier", " David_Alan Grier")
    .replace("Tyler James Williams", "Tyler_James Williams")
    .replace("Kristin Scott Thomas", "Kristin_Scott Thomas")
    .replace("John Carroll Lynch", "John_Carroll Lynch")
    .replace("Sheila_E.", "Sheila E.")
    .replace("Mary Kate Wiles", "Mary_Kate Wiles")
    .replace("D._L._Hughley", "D. L._Hughley")
    .replace("R. Martin Klein", "R. Martin_Klein")
    .replace("Lionel Mark Smith", "Lionel_Mark Smith")
    .replace("Philip Baker Hall", "Philip_Baker Hall")
    .replace("R. D._Call", "R._D. Call")
    .replace("R._Martin_Klein", "R_Martin Klein")
    .replace("Riley Thomas Stewart", "Riley Thomas_Stewart")
    .replace("J.R._Villarreal", "J._R. Villarreal")
    .replace("David A.R._White", "David A._R._White")
    .replace("Melissa Joan Hart", "Melissa Joan_Hart")
    .replace("Macody Lund", "Macody_Lund")
    .replace("T.R._Knight", "T. R._Knight")
    .replace("Billy Bob Thornton", "Billy Bob_Thornton")
    .replace("Marcia Gay Harden", "Marcia Gay_Harden")
    .replace("Jamie Lee Curtis", "Jamie Lee_Curtis")
    .replace("Keegan Connor Tracy", "Keegan Connor_Tracy")
    .replace("J._Smith-Cameron", "J. Smith-Cameron")
    .replace("Michelle Simone Miller", "Michelle_Simone Miller")
    .replace("Patch Mackenzie_E. ", "Patch Mackenzie E._")
    .replace("E._Danny Murphy_E. ", "E._Danny Murphy E. ")
    .replace("Max von Sydow", "Max von_Sydow")
    .replace("Anna Deavere Smith", "Anna Deavere_Smith")
    .replace("Vanessa Lee Chester", "Vanessa Lee_Chester")
    .replace("Lara Jean Chorostecki", "Lara Jean_Chorostecki")
    .replace("Seann William Scott", "Seann William_Scott")
    .replace("Holly Marie Combs", "Holly Marie_Combs")
    .replace("T._R._Knight", "T. R._Knight")
    .replace("Michael Reilly Burke", "Michael Reilly_Burke")
    .replace("Xiao Shen Yang", "Xiao Shen_Yang")
    .replace("Benicio del Toro", "Benicio del_Toro")
    .replace("David Ogden Stiers", "David Ogden_Stiers")
    .replace("Helena Bonham Carter", "Helena Bonham_Carter")
    .replace("Susan May Pratt", "Susan May_Pratt")
    .replace("Nacio Herb Brown", "Nacio Herb_Brown")
    .replace("Brian Austin Green", "Brian Austin_Green")
    .replace("Raoul Max Trujillo", "Raoul Max_Trujillo")
    .replace("Stephen Barker Turner", "Stephen Barker_Turner")
    .replace("Courtney Taylor Burness", "Courtney Taylor_Burness")
    .replace("Sophie Kennedy Clark", "Sophie Kennedy_Clark")
    .replace("Sarah Jessica Parker", "Sarah Jessica_Parker")
    .replace("Jennifer Jason Leigh", "Jennifer Jason_Leigh")
    .replace("Christopher Nicholas Smith", "Christopher Nicholas_Smith")
    .replace("Joe Lo Truglio", "Joe Lo_Truglio")
    .replace(" Jonathan Rhys Meyers", " Jonathan Rhys_Meyers")
    .replace("Caleb Landry Jones", "Caleb Landry_Jones")
    .replace("Jessica Brooks Grant", "Jessica Brooks_Grant")
    .replace("Tommy Lee Jones", "Tommy Lee_Jones")
    .replace("Grace Moretz", "Grace_Moretz")
    .replace("Isild Le Besco", "Isild Le_Besco")
    .replace("Jonathan Rhys Meyers", "Jonathan Rhys_Meyers")
    .replace("Perry Laylon Ojeda", "Perry Laylon_Ojeda")
    .replace("Kirby Bliss Blanton", "Kirby Bliss_Blanton")
    .replace("Omar Benson Miller", "Omar Benson_Miller")
    .replace("Robert De Niro", "Robert De_Niro")
    .replace("Garette Ratliff Henson", "Garette Ratliff_Henson")
    .replace("W. Bush", "W._Bush")
    .replace("James Badge Dale", "James Badge_Dale")
    .replace("Penelope Ann Miller", "Penelope Ann_Miller")
    .replace("Anthony Stewart Head", "Anthony Stewart_Head")
    .replace("Jack La Rue", "Jack La_Rue")
    .replace("Anthony Michael Hall", "Anthony Michael_Hall")
    .replace("Neil Patrick Harris", "Neil Patrick_Harris")
    .replace("e Le Calm", "e Le_Calm")
    .replace("David James Elliott", "David James_Elliott")
    .replace("Jackie Earle Haley", "Jackie Earle_Haley")
    .replace("Kate del Castillo", "Kate del_Castillo")
    .replace("Jennifer Schwalbach Smith", "Jennifer Schwalbach_Smith")
    .replace("Michele Lamar Richards", "Michele Lamar_Richards")
    .replace("Peter Mark Richman", "Peter Mark_Richman")
    .replace("Lee Van Cleef", "Lee Van_Cleef")
    .replace("Philip Seymour Hoffman", "Philip Seymour_Hoffman")
    .replace("Evan Rachel Wood", "Evan Rachel_Wood")
    .replace("Carice van Houten", "Carice van_Houten")
    .replace("Carlos Rodr", "Carlos_Rodr")
    .replace("Michael Dean Jacobs ", "Michael Dean_Jacobs ")
    .replace("Thomas Haden Church ", "Thomas Haden_Church ")
    .replace("Brian Keith Allen", "Brian Keith_Allen")
    .replace("David Tristan Birkin", "David Tristan_Birkin")
    .replace("Michael Dean Jacobs", "Michael Dean_Jacobs")
    .replace("Joe Don Baker", "Joe Don_Baker")
    .replace("Gabrielle Lopes Benites", "Gabrielle Lopes_Benites")
    .replace("Ki Hong Lee", "Ki Hong_Lee")
    .replace("Jason Scott Lee", "Jason Scott_Lee")
    .replace("William Lee Scott", "William Lee_Scott")
    .replace("Eric Christian Olsen", "Eric Christian_Olsen")
    .replace("David Hyde Pierce", "David Hyde_Pierce")
    .replace("Michael Kenneth Williams", "Michael Kenneth_Williams")
    .replace("Will Yun Lee", "Will Yun_Lee")
    .replace("Julie 'Jules' Urich", "Julie 'Jules'_Urich")
    .replace("Bong Soo Han", "Bong Soo_Han")
    .replace("Robert Sean Leonard", "Robert Sean_Leonard")
    .replace("Lisa Ann Walter", "Lisa Ann_Walter")
    .replace("Jose Pablo Cantillo", "Jose Pablo_Cantillo")
    .replace("Daniel Hugh Kelly", "Daniel Hugh_Kelly")
    .replace("Clifton Collins Jr", "Clifton Collins_Jr.")
    .replace("Raphael de la Sierra", "Raphael de_la_Sierra")
    .replace("Birgitte Hjort Sørensen", "Birgitte Hjort_Sørensen")
    .replace("Mohammad Nadir Khwaja", "Mohammad Nadir_Khwaja")
    .replace("David Patrick Kelly", "David Patrick_Kelly")
    .replace("Tamar van den Dop", "Tamar van_den_Dop")
    .replace("Jean-Claude Van Damme", "Jean-Claude Van-Damme")
    .replace("Fedja van Huêt", "Fedja van_Huêt")
    .replace("Raúl Juliá", "Raúl Juliá")
    .replace("Julanne Chidi Hill", "Julanne Chidi_Hill")
    .replace("Sarah Wayne Callies", "Sarah WayneCallies")
    .replace("Lou Diamond Phillips", "Lou Diamond_Phillips")
    .replace("Joanna 'JoJo' Levesque", "Joanna 'JoJo'_Levesque")
    .replace("Julio Oscar Mechoso", "Julio Oscar_Mechoso")
    .replace("Michael Clarke Duncan", "Michael Clarke_Duncan")
    .replace("Jean Michel Paré", "Jean Michel Paré")
    .replace("Mary Kay Place", "Mary Kay_Place")
    .replace("Joseph Julian Soria", "Joseph Julian_Soria")
    .replace("Harry Dean Stanton", "Harry Dean_Stanton")
    .replace("Andrew Dice Clay", "Andrew Dice_Clay")
    .replace(" Danielle von Zerneck", " Danielle von_Zerneck")
    .replace("Debra Jo Rupp", "Debra Jo_Rupp")
    .replace("Juan José Campanella", "Juan José_Campanella")
    .replace("Juan Eduardo Palacios", "Juan Eduardo_Palacios")
    .replace("Tim Blake Nelson", "Tim Blake_Nelson")
    .replace("Mary Elizabeth Winstead", "Mary Elizabeth_Winstead")
    .replace("Mary Tyler Moore", "Mary Tyler_Moore")
    .replace("Edward James Olmos", "Edward James_Olmos")
    .replace("Daphnée Duplaix Samuel", "Daphnée Duplaix_Samuel")
    .replace("LL Cool J", "LL Cool_J")
    .replace("Thomas Ian Griffith", "Thomas Ian_Griffith")
    .replace("Makenzie Vega Norfolk", "Makenzie Vega_Norfolk")
    .replace("David Jason Perez", "David Jason_Perez")
    .replace("Charles Martin Smith", "Charles Martin_Smith")
    .replace("Maï Anh Le", "Maï Anh_Le")
    .replace("Jaran 'See Tao' Petcharoen", "Jaran 'See Tao'_Petcharoen")
    .replace("Stéphanie Lagarde", "Stéphanie Lagarde")
    .replace("Vincent Byrd Le_Sage", "Vincent Byrd_Le_Sage")
    .replace("Ronnie Gene Blevins", "Ronnie Gene_Blevins")
    .replace(" James Earl Jones", " James Earl_Jones")
    .replace("Bryce Dallas Howard", "Bryce Dallas_Howard")
    .replace("De_Anna Joy Brooks", "De_Anna Joy_Brooks")
    .replace("F.A._Turner", "F. A._Turner")
    .replace("Angelo Barra Moreira", "Angelo Barra_Moreira")
    .replace("Chao Li Chi", "Chao Li_Chi")
    .replace("Tony Leung Chiu-Wai", "Tony Leung_Chiu-Wai")
    .replace("Rae Dawn Chong", "Rae Dawn_Chong")
    .replace("Tom Everett Scott", "Tom Everett_Scott")
    .replace("Robert John Burke", "Robert John_Burke")
    .replace("Michael Bailey Smith", "Michael Bailey_Smith")
    .replace("Jessica Brown Findlay", "Jessica Brown_Findlay")
    .replace("Joey Lauren Adams", "Joey Lauren_Adams")
    .replace("Jeremy James Kissner", "Jeremy James_Kissner")
    .replace("Natasha Gregson Wagner", "Natasha Gregson_Wagner")
    .replace("Mark Boone Junior", "Mark Boone_Junior")
    .replace("Nolan Gerard Funk", "Nolan Gerard_Funk")
    .replace("Van_Johnson", "Van Johnson")
    .replace("James Van_Der Beek", "James Van_Der_Beek")
    .replace("Merrie Lynn Ross", "Merrie Lynn_Ross")
    .replace("Philip Chan Yan-Kin", "Philip Chan_Yan-Kin")
    .replace("Sara Malakul Lane", "Sara Malakul_Lane")
    .replace("Rachael Leigh Cook", "Rachael Leigh_Cook")
    .replace("Michael Jai White", "Michael Jai_White")
    .replace("Chad Michael Murray", "Chad Michael_Murray")
    .replace("Michelle Van_Der Water", "Michelle Van_Der_Water")
    .replace("Tamar van_den Dop", "Tamar van_den_Dop")
    .replace("Jamie Campbell Bower", "Jamie Campbell_Bower")
    .replace("Frederique van_der Wal", "Frederique van_der_Wal")
    .replace("Randall Duk Kim", "Randall Duk_Kim")
    .replace("Billy Ray Cyrus", "Billy Ray_Cyrus")
    .replace("George Buck Flower", "George Buck_Flower")
    .replace("Callum Keith Rennie", "Callum Keith_Rennie")
    .replace("Damian Jewan Lee", "Damian Jewan_Lee")
    .replace("David Roland Frank", "David Roland_Frank")
    .replace("Ella Rae Peck", "Ella Rae_Peck")
    .replace("Christopher Evan Welch", "Christopher Evan_Welch")
    .replace("Mary Elizabeth Mastrantonio", "Mary Elizabeth_Mastrantonio")
    .replace("Elizabeth of Toro", "Elizabeth of_Toro")
    .replace("Shah Rukh Khan", "Shah Rukh_Khan")
    .replace("Lisa Gay Hamilton", "Lisa Gay_Hamilton")
    .replace("Sarah Jessica Parker", "Sarah Jessica_Parker")
    .replace("Maggie Elizabeth Jones", "Maggie Elizabeth_Jones")
    .replace("Haley Joel Osment", "Haley Joel_Osment")
    .replace("Anna Maria Horsford", "Anna Maria_Horsford")
    .replace("Joel David Moore", "Joel David_Moore")
    .replace("Holly Robinson Peete", "Holly Robinson_Peete")
    .replace("Julie Ann Emery", "Julie Ann_Emery")
    .replace("Lynn 'Red' Williams", "Lynn 'Red'_Williams")
    .replace("Thomas Haden Church", "Thomas Haden_Church")
    .replace("John Phillip Law", "John Phillip_Law")
    .replace("Hadley Belle Miller", "Hadley Belle_Miller")
    .replace("Audrey Lynn Tennent", "Audrey Lynn_Tennent")
    .replace("Rickey D'Shon Collins", "Rickey D'Shon_Collins")
    .replace("Edward Everett Horton", "Edward Everett_Horton")
    .replace("Sarah Michelle Gellar ", "Sarah Michelle_Gellar ")
    .replace("Jon Bon Jovi", "Jon Bon_Jovi")
    .replace("Amber Rose Revah", "Amber Rose_Revah")
    .replace("Klaus Maria Brandauer", "Klaus Maria_Brandauer")
    .replace("M.L. Piyapas Bhirombhakdi", "M.L. Piyapas_Bhirombhakdi")
    .replace("Godfrey ^ Cambridge", "Godfrey Cambridge")
    .replace("Christopher Corey Smith", "Christopher Corey_Smith")
    .replace("Dee Dee Greene", "Dee Dee_Greene")
    .replace("Billy Dee Williams", "Billy Dee_Williams")
    .replace("Dee Bradley Bak", "Dee Bradley_Bak")
    .replace("Sophia Taylor Ali", "Sophia Taylor_Ali")
    .replace("Thomas Ian Nicholas", "Thomas Ian_Nicholas")
    .replace("Meredith Scott Lynn", "Meredith Scott_Lynn")
    .replace("Jeppe Beck Laursen", "Jeppe Beck_Laursen")
    .replace("Evy Kasseth Røsten", "Evy Kasseth_Røsten")
    .replace("Stig Frode Henriksen", "Stig Frode_Henriksen")
    .replace("Eddie Kaye Thomas", "Eddie Kaye_Thomas")
    .replace("Alexandra Maria Lara", "Alexandra Maria_Lara")
    .replace("Sheri Moon Zombie", "Sheri Moon_Zombie")
    .replace("Juan Carlos Montoya", "Juan Carlos_Montoya")
    .replace("Allan Bryan Weku", "Allan Bryan_Weku")
    .replace("Luis Fernando Peña", "Luis Fernando_Peña")
    .replace("Harold House Moore", "Harold House_Moore")
    .replace("Catalina Sandino Moreno", "Catalina Sandino_Moreno")
    .replace("Ana Claudia Talancón", "Ana Claudia_Talancón")
    .replace("John Canada Terrell", "John Canada_Terrell")
    .replace("Christie Lynn Smith", "Christie Lynn_Smith")
    .replace("Anthony 'Citric' Campos", "Anthony 'Citric'_Campos")
    .replace("Soha Ali Khan", "Soha Ali_Khan")
    .replace("Jonathan Taylor Thomas", "Jonathan Taylor_Thomas")
    .replace("Lily Autumn Page", "Lily Autumn_Page")
    .replace("Lara Jill Miller", "Lara Jill_Miller")
    .replace("Lara Flynn Boyle", "Lara Flynn_Boyle")
    .replace("Jennifer Love Hewitt", "Jennifer Love_Hewitt")
    .replace("Josep Maria Pou", "Josep Maria_Pou")
    .replace("James Anthony Pearson", "James Anthony_Pearson")
    .replace("Jonny Lee Miller", "Jonny Lee_Miller")
    .replace("Sisqó", "Sisqó ^")
    .replace("Morgan Peter Brown ", "Morgan Peter_Brown ")
    .replace("James Francis Kelly_III", "James Francis_Kelly_III")
    .replace("María Conchita Alonso", "María Conchita_Alonso")
    .replace("Lisa Hart Carroll", "Lisa Hart_Carroll")
    .replace("Per Christian Ellefsen", "Per Christian_Ellefsen")
    .replace("Marit Pia Jacobsen", "Marit Pia_Jacobsen")
    .replace("Erik Per Sullivan", "Erik Per_Sullivan")
    .replace("Juan Maria Almonte", "Juan Maria_Almonte")
    .replace("Nicole Ari Parker", "Nicole Ari_Parker")
    .replace("Gary 'G. Thang' Johnson", "Gary 'G._Thang'_Johnson")
    .replace("  ", " ")
    .replace("  ", " ")
    .replace("Christa Brittany Allen", "Christa Brittany_Allen")
    .replace("Jamyang Jamtsho Wangchuk", "Jamyang Jamtsho_Wangchuk")
    .replace("Ahmad Khan Mahmoodzada", "Ahmad Khan_Mahmoodzada")
    .replace("Patricia Reyes Spíndola", "Patricia Reyes_Spíndola")
    .replace("June Carter Cash", "June Carter_Cash")
    .replace("Harley Jane Kozak", "Harley Jane_Kozak")
    .replace("Jodi Lyn O'Keefe", "Jodi Lyn_O'Keefe")
    .replace("Lisa Roberts Gillan", "Lisa Roberts_Gillan")
    .replace("Eva Amurri Martino", "Eva Amurri_Martino")
    .replace("Jeffrey Dean Morgan", "Jeffrey Dean_Morgan")
    .replace("Bergüzar Korel", "Bergüzar Korel")
    .replace("Muhammed Necati Şaşmaz", "Muhammed Necati_Şaşmaz")
    .replace("Gordon Lam Ka-Tung", "Gordon Lam_Ka-Tung")
    .replace("Gael García Bernal", "Gael García_Bernal")
    .replace("Stephen Tyrone Williams", "Stephen Tyrone_Williams")
    .replace("Christopher Jordan Wallace", "Christopher_Jordan Wallace")
    .replace("Eddie Cheung Siu-Fai", "Eddie Cheung_Siu-Fai")
    .replace("Michael Robert Brandon", "Michael Robert_Brandon")
    .replace("Lesley Ann Warren", "Lesley Ann_Warren")
    .replace("Natalie Stephany Aguilar", "Natalie Stephany_Aguilar")
    .replace("Louise Lemoine Torrès", "Louise Lemoine_Torrès")
    .replace("Emilio Tuki Hito", "Emilio Tuki_Hito")
    .replace("Benjamin Jay Davis", "Benjamin Jay_Davis")
    .replace("Abu George Shibli ", "Abu George_Shibli ")
    .replace("Sheryl Lee Ralph", "Sheryl Lee_Ralph")
    .replace("Gordon Liu Chia-Hui", "Gordon Liu_Chia-Hui")
    .replace("Abu George Shibli", "Abu George_Shibli")
    .replace("Sarah Jane Morris", "Sarah Jane_Morris")
    .replace("Wen Bin Huang", "Wen Bin_Huang")
    .replace("John Michael Higgins", "John Michael_Higgins")
    .replace("Wendy Raquel Robinson", "Wendy Raquel_Robinson")
    .replace("Monique Gabriela Curnen", "Monique Gabriela_Curnen")
    .replace("Adrián Alonso Barona", "Adrián Alonso_Barona")
    .replace("William Morgan Sheppard", "William Morgan_Sheppard")
    .replace("Weird Al", "Weird_Al")
    .replace("Putu Dinda Pratika", "Putu Dinda_Pratika")
    .replace("Puti Sri Candra Dewi", "Puti Sri_Candra_Dewi")
    .replace("Ni Made Megahadi Pratiwi", "Ni Made_Megahadi_Pratiwi")
    .replace("Robin Atkin Downes", "Robin Atkin_Downes")
    .replace("Rima Te Wiata", "Rima Te_Wiata")
    .replace("Tony Leung Ka-Fai", "Tony Leung_Ka-Fai")
    .replace("Marcus Carl Franklin", "Marcus Carl_Franklin")
    .replace("Roger Guenveur Smith", "Roger Guenveur_Smith")
    .replace("Deborah Kara Unger", "Deborah Kara_Unger")
    .replace("James Arnold Taylor", "James Arnold_Taylor")
    .replace("Jacqueline MacInnes Wood", "Jacqueline MacInnes_Wood")
    .replace("Wotan Wilke Möhring", "Wotan Wilke_Möhring")
    .replace("Larry the_Cable Guy", "Larry the_Cable_Guy")
    .replace("Sean Patrick Thomas", "Sean Patrick_Thomas")
    .replace("Patrick_Thomas Eve", "Patrick_Thomas Eve ^")
    .replace("Jayvee Mai The_Hiep", "Jayvee Mai_The_Hiep")
    .replace("Eva Marie Saint", "Eva Marie_Saint")
    .replace("Anthony Tony Shalhoub", "Anthony Tony_Shalhoub")
    .replace("Sean Michael Afable", "Sean Michael_Afable")
    .replace("Ana Maria Guran", "Ana Maria_Guran")
    .replace("Kitty Zhang Yuqi", "Kitty Zhang_Yuqi")
    .replace("Fred Dalton Thompson", "Fred Dalton_Thompson")
    .replace("Jill Marie Jones", "Jill Marie_Jones")
    .replace("Karin Anna Cheung", "Karin Anna_Cheung")
    .replace("Anna Claire Sneed", "Anna Claire_Sneed")
    .replace("Jonathan Ke Quan", "Jonathan Ke_Quan")
    .replace("Mary Kay Bergman", "Mary Kay_Bergman")
    .replace("Mary Lynn Rajskub", "Mary Lynn_Rajskub")
    .replace(" Ellen Hamilton Latzen", " Ellen Hamilton_Latzen")
    .replace("Ana López Mercado", "Ana López_Mercado")
    .replace("Jonathan Erickson Eisley", "Jonathan Erickson_Eisley")
    .replace("Anika Noni Rose", "Anika Noni_Rose")
    .replace("Amber Marie Bollinger", "Amber Marie_Bollinger")
    .replace("Tung Thanh Tran", "Tung Thanh_Tran")
    .replace("James Patrick Stuart", "James Patrick_Stuart")
    .replace("Lou Taylor Pucci", "Lou Taylor_Pucci")
    .replace("Jamie Renée Smith", "Jamie Renée_Smith")
    .replace("Jean François Heckel", "Jean François_Heckel")
    .replace("Tupac Amaru Shakur", "Tupac Amaru_Shakur")
    .replace("Yasmine Al Massri", "Yasmine Al_Massri")
    .replace("Jeff Daniel Phillips", "Jeff Daniel_Phillips")
    .replace("Malcolm David Kelley", "Malcolm David_Kelley")
    .replace("Leon Isaac Kennedy", "Leon Isaac_Kennedy")
    .replace("Sean Patrick Flanery", "Sean Patrick_Flanery")
    .replace("R._D._Call", "R. D._Call")
    .replace("David Della Rocco", "David Della_Rocco")
    .replace("Elina Abai Kyzy", "Elina Abai_Kyzy")
    .replace("Aishwarya Rai Bachchan", "Aishwarya Rai_Bachchan")
    .replace("Mads Sjøgård Pettersen", "Mads Sjøgård_Pettersen")
    .replace("Robert Daniel Sloan", "Robert Daniel_Sloan")
    .replace("David Lee Smith", "David Lee_Smith")
    .replace("Vanessa Bell Calloway", "Vanessa Bell_Calloway")
    .replace("Gralen Bryant Banks", "Gralen Bryant_Banks")
    .replace("David Sanin Paz", "David Sanin_Paz")
    .replace("Brad William Henke", "Brad William_Henke")
    .replace(" Lail Molly Hagan", "_Lail Molly Hagan")
    .replace("Ten Years After", "Ten Years_After")
    .replace("Roy Richard Grinker", "Roy Richard_Grinker")
    .replace("D. David Morin", "D. David_Morin")
    .replace("Sumeet Darshan Dobhal", "Sumeet Darshan_Dobhal")
    .replace("Fadi Abi Samra", "Fadi Abi_Samra")
    .replace("Matthew Gray Gubler", "Matthew Gray_Gubler")
    .replace("Ernesto Gómez Cruz", "Ernesto Gómez_Cruz")
    .replace("Cyndi Mayo Davis", "Cyndi Mayo_Davis")
    .replace("Ian Michael Smith ", "Ian Michael_Smith ")
    .replace("Charles Henry Wyson", "Charles Henry_Wyson")
    .replace("Jesse Lee Soffer", "Jesse Lee_Soffer")
    .replace("Stephen Campbell Moore ", "Stephen Campbell_Moore ")
    .replace("Spencer Treat Clark", "Spencer Treat_Clark")
    .replace("Kassovitz Rufus", "Kassovitz Rufus ^")
    .replace("John Patrick Amedori", "John Patrick_Amedori")
    .replace("Robert Ellis Orrall", "Robert Ellis_Orrall")
    .replace("Skye McCole Bartusiak", "Skye McCole_Bartusiak")
    .replace("Kate Lynn Evans ", "Kate Lynn_Evans ")
    .replace(" Milewski ", "_Milewski ")
    .replace("Sean Cameron Michael", "Sean Cameron_Michael")
    .replace("Jane Galloway Heitz", "Jane Galloway_Heitz")
    .replace("Kate Lynn Evans", "Kate Lynn_Evans")
    .replace("Thomas Francis Walsh_III", "Thomas Francis_Walsh_III")
    .replace("Olivia Taylor Dudley", "Olivia Taylor_Dudley")
    .replace("Ingrid Bolsø Berdal", "Ingrid Bolsø_Berdal")
    .replace("Kevin Peter Hall", "Kevin Peter_Hall")
    .replace("Ginés García Millán", "Ginés García_Millán")
    .replace(" María Mercedes Villagra ", " María Mercedes_Villagra ")
    .replace("Amanda Redman ^", "Amanda Redma")
    .replace("Nouva Monika Wahlgren", "Nouva Monika_Wahlgren")
    .replace("Jamil Walker Smith", "Jamil Walker_Smith")
    .replace("Jean Michel Paré", "Jean Michel_Paré")
    .replace("Jon Ted Wynne", "Jon Ted_Wynne")
    .replace("Christoph Maria Herbst", "Christoph_Maria Herbst")
    .replace("Mary Beth Hurt", "Mary Beth_Hurt")
    .replace("Rae'Ven Larrymore_Kelly", "Rae'Ven Larrymore_Kelly")
    .replace("Taylor Scott Olson", "Taylor Scott_Olson")
    .replace("Henry Ian Cusick ", "Henry Ian_Cusick ")
    .replace("Maryiam Palvin Almani", "Maryiam Palvin_Almani")
    .replace("L. Scott Caldwel", "L. Scott_Caldwel")
    .replace("Roscoe Lee Browne", "Roscoe Lee_Browne")
    .replace("Rae'Ven Larrymore Kelly", "Rae'Ven Larrymore_Kelly")
    .replace("Dakota Blue Richards", "Dakota Blue_Richards")
    .replace("Jerome Elston Scott", "Jerome Elston_Scott")
    .replace("Reza Sixo Safai", "Reza Sixo_Safai")
    .replace("Eric Allan Kramer", "Eric Allan_Kramer")
    .replace("John Cameron Mitchell", "John Cameron_Mitchell")
    .replace("Anthony Ray Parker", "Anthony Ray_Parker")
    .replace("Wen Yann Shih", "Wen Yann_Shih")
    .replace("Tran Nu Yên-Khê", "Tran Nu_Yên-Khê")
    .replace("Gregory Russell Cook", "Gregory Russell_Cook")
    .replace("Lauren Lee Smith", "Lauren Lee_Smith")
    .replace(" Michael Aaron Milligan", " Michael Aaron_Milligan")
    .replace("Sydney Tamiia Poitier", "Sydney Tamiia_Poitier")
    .replace("Emma Eliza Regan", "Emma Eliza_Regan")
    .replace("Aja Naomi King", "Aja Naomi_King")
    .replace("Connor Christopher Levins", "Connor Christopher_Levins")
    .replace("Sandra Ellis Lafferty", "Sandra Ellis_Lafferty")
    .replace("Thomas Bo Larsen", "Thomas Bo_Larsen")
    .replace("Gian Maria Volonté", "Gian Maria_Volonté")
    .replace("Ólafur Darri Ólafsson", "Ólafur Darri_Ólafsson")
    .replace("June Diane Raphael", "June Diane_Raphael")
    .replace("Catherine Lloyd Burns", "Catherine Lloyd_Burns")
    .replace("Alyn Lind", "Alyn_Lind")
    .replace("Travis Aaron Wade", "Travis Aaron_Wade")
    .replace("Moses Jacob Storm ", "Moses Jacob_Storm ")
    .replace("Ricky Dean Logan", "Ricky Dean_Logan")
    .replace("Anne Louise Hassing ", "Anne Louise_Hassing ")
    .replace("Ty Thomas Reed", "Ty Thomas_Reed")
    .replace(" Hui Lou Chen", " Hui Lou_Chen")
    .replace("Harley Quinn Smith", "Harley Quinn_Smith")
    .replace("Paula Jai Parker", "Paula Jai_Parker")
    .replace("Hui Lou Chen", "Hui Lou_Chen")
    .replace("Keshia Knight Pulliam", "Keshia Knight_Pulliam")
    .replace("Hatha Yogi Baba", "Hatha Yogi_Baba")
    .replace("Pant Shirt Baba", "Pant Shirt_Baba")
    .replace("Shriman Umeshanad Brahmachari", "Shriman Umeshanad_Brahmachari")
    .replace("Patrick Tse Yin", "Patrick Tse_Yin")
    .replace("Adam David Thompson", "Adam David_Thompson")
    .replace("Vicellous Reon Shannon", "Vicellous Reon_Shannon")
    .replace("Machine Gun Kelly ", "Machine Gun_Kelly ")
    .replace("David W. Ross", "David W._Ross")
    .replace("John Ross Bowie", "John Ross_Bowie")
    .replace("John Benjamin Hickey", "John Benjamin_Hickey")
    .replace("Tara Alice Scully", "Tara Alice_Scully")
    .replace("Dick Anthony Williams", "Dick Anthony_Williams")
    .replace("James Robertson Justice", "James Robertson_Justice")
    .replace("Sophie Charlotte Conrad", "Sophie Charlotte_Conrad")
    .replace("Juan Carlos Hernández", "Juan Carlos_Hernández")
    .replace("Juan Carlos Copes", "Juan Carlos_Copes")
    .replace("Lisa Nicole Carson", "Lisa Nicole_Carson")
    .replace("Charles Malik Whitfield", "Charles Malik_Whitfield")
    .replace("Paco Christian Prieto", "Paco Christian_Prieto")
    .replace("Rocky Mayor Anderson", "Rocky Mayor_Anderson")
    .replace("Jonathan Daniel Brown", "Jonathan Daniel_Brown")
    .replace("Mia Drake Inderbitzin", "Mia Drake_Inderbitzin")
    .replace("John Bennett Perry", "John Bennett_Perry")
    .replace("Wilbur 'Hi-Fi' White", "Wilbur 'Hi-Fi'_White")
    .replace("Lenny Von Dohlen", "Lenny Von_Dohlen")
    .replace("Christopher Robin Miller", "Christopher Robin_Miller")
    .replace("Chase Wright Vanek", "Chase Wright_Vanek")
    .replace("Miguel Ángel Solá", "Miguel Ángel_Solá")
    .replace("José Luis García Pérez", "José_Luis García_Pérez")
    .replace("Padraic Delaney", "Pádraic Delaney")

  )











}
